### ISSUE TITLE
Save config file

### ISSUE THREAD

**Issue by bazilinskyy** [bazilinskyy/coupled-sim#3]
Save file with config vars for each client before the experiment to be able to check the status of each client after the experiment.

**Comment by bazilinskyy** [comment]
@ir-L-Kooijman, do you remember what caused a need for such a request?

**Comment by Lynx32** [comment]
I don't really understand what you want to log here. What vars?

**Comment by bazilinskyy** [comment]
I honestly don't remember myself. During the demo, we encountered that we did not know something for each of the agents. This issue is more or a placeholder. @ir-L-Kooijman, if you can't remember what was the problem either, please close this issue.

**Comment by LarsKooijman** [comment]
The problem was that if after an experiment we chuck the data of the Clients and the Hosts in 1 folder, we can never tell which client/host had which "Role" etc. 
It would be nice if we are able to get a text box for each client/host where we can type in the assigned role for example, and that that name is in the filename of the log file. I was thinking about a similar text box that is used now to type in the IP address. 
Or if it's possible to assign these filenames names for client & host data from the Host PC, that would be even better. 

For example, client 1 will be a Manual Driver and then the log data will be named:
WorldRoot-ClientLog-ManualDriver-2019_09_11_14_36_52.

**Comment by Lynx32** [comment]
Got it. Will do.
